export interface RegisterModel {
  gender: string,
  email: string,
  phoneNumber: string,
  nationalID: string,
  dateOfBirth: Date,
  jobTitle: string,
  type: string,
  accountStatus: string,
  city: string,
  province: string,
  country: string,
  street: string,
  nationalIdFront: string,
  nationalIdBack: string,
  profilePicture: string,
  first: string,
  firstMiddle: string,
  secondMiddle: string,
  last: string,
  password: string
}
