export const Arabic: any = {
  dir: "rtl",
  lang: "English",
  font: "cairoFont",
  navFloat: "",
  arabicClass: "arabic",
  rowReverse: "flex-row-reverse",
  menuStyle: "arabicMenu",
  menuCloseStyle: "arabicCloseButton",
  textAlign: "text-right",
  textAlignReverse: "text-left",
  FlexAlignItems: "align-items-end",
  justifyContent: "justify-content-end",
  NoRequest: "لا يوجد طلبات",
  flexDIr: "flex-row-reverse",
  copyRights1: "كل الحقوق محفوظة |",
  terms: "شروط",
  policy: "احكام",
  aboutHeaderOne: "معلومات دقيقة وشفافة ",
  aboutHeaderTwo: "مقارنات محايدة ",
  aboutHeaderThree: "معلومات عالية الجودة",
  aboutHeaderFour: "أدوات فريدة",
  layout: {
    Home: "الرئيسية",
    about: "المزيد عنا",
    contact: "اتصل بنا",
    login: "الدخول",
    logout: "الخروج",
    service: "خدماتنا",
    requests: "طلبات الخدمات",
    links: "تصفح سريع",
    Loans: "قروض",
    personalLoans: "قروض شخصية",
    accounts: "حسابات",
    investments: "الاستثمارات",
    creditCards: "بطاقات الائتمان",

  },
  Home: {
    More: "المزيد",
    aboutTitle: "لماذا نحن",
    AboutContent: "نحن ملتزمون بتقديم أفضل خدمة وساطة مالية من حيث التداول والبحث وذلك من خلال. ",
    creditTitle: "كيف يمكننا أن نفعل ذلك؟",
    creditDesc: "نعمل كشريك لتقديم المنتجات والخدمات المالية التي تجعل الخدمات المصرفية آمنة وبسيطة ومريحة.",
    
  },
  about: {
    title1: "من نحن",
    content1: 'نحن شركة ناشئة بفريق صغير و لكنه فعال للغاية و متحمس. نحن نساعدك في اجراء مقارنات القروض المتاحة للعمالاء ومقارنة بطاقات االئتمان داخل الإمارات العربية المتحدة. من خلال  تلك المقارنات، نساعدك على تحديد الخيارات التي ستتيح لك التوفير والاستخدام الامثل مع أفضل وأيسر الامتيازات.',
    title2: "كيف يمكننا أن نفعل ذلك؟ ",
    content2: "أولا نحن فريق من الماليين الغير التقليديين في المجالات المصرفية ولدينا فهم عميق للنظام المصرفي للأفراد في الامارات العربية المتحدة .خبرتنا في مجالات خطط االائتمان والاكتتاب والمبيعات و استراتيحية المبيعات والعمليات وخدمة العمالاء والتكنولوجيا والتسويق. تتيح خدماتنا لمستخدمينا تشكيل مجموعة جيدة من حلول التمويل الخاص، من بطاقات المكافآت ماستركارد داخل الإمارات العربية المتحدة، إلى القروض غير العامة، إلى بطاقات الائتمان الإسلامية، إلى العديد من التطبيقات غيرذلك."
  },
  invalid: {
    invalidEmail: "البريد الالكتروني غير صحيح",
    requiredEmail: "ادخل البريد الالكتروني",
    emailPattern : "يجب أن يكون تنسيق البريد الإلكتروني صحيحًا",
    requiredPassword: "ادخل الرقم السري",
    InvalidPassword: "يجب أن يحتوي على حرف أبجدي صغير واحد على الأقل ، وحرف أبجدي كبير واحد على الأقل ، وحرف رقمي واحد على الأقل ، وحرف خاص واحد على الأقل ، ويجب أن يتكون من ثمانية أحرف أو أكثر.",
    InvalidConfirmPassword: "كلمة المرور غير مطابقة لتأكيد كلمة المرور ",
    requiredMobileNumber: "ادخل رقم الهاتف",
    InvalidMobileNumber: "رقم غير صحيح",
    InvalidName: "اسم غير صحيح",
    requiredDateOfBirth: "ادخل تاريخ الميلاد",
    requiredName: "ادخل الاسم",
    requiredAddress: "ادخل العنوان",
    requiredProvince: "ادخل المحافظة",
    requiredCountry: "ادخل البلد",
    requiredcity: "ادخل المدينة",
    requiredStreet: "ادخل الشارع",
    requiredJobTitle: "ادخل المسمي الوظيفي",
    requiredNationalID: "ادخل رقم الهوية",
    invalidNationalID:"رقم الهوية اقل من 14 رقم",
    namePattern: "يجب ألا يحتوي الاسم على أرقام أو رموز أو مسافات",
    invalidLogin: "تأكد من البيانات",
    invalidRegister: "خطأ في تقديم الطلب ، يرجى المحاولة مرة أخرى",
    loginRedirect: "سيتم إعادة توجيهك بعد قليل",
    required: "مطلوب",
  },
  subscribe: {
    subscribeNw: "اشترك الان",
    send: "ارسال",
    subscribed: "تم الاشتراك بالفعل",
  },
  serviceCarousel: {
    title: "خدماتنا المميزة",
    title2: "يوصى بأنواع مختلفة من الخدمات لك"

  },
  backsCarousel: {
    title: "مزدو الخدمة المميزون ",
    content: "هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها.",
  },
  login: {
    wlc: "مرحبا بك في",
    forgetPassword: "نسيت كلمة المرور؟ ",
    desc: "نسهل على الجميع الاستثمار في الخدمات المصرفية",
    login: "الدخول",
    donHaveAcc: "ليس لديك حساب ،",
    createAcc: "إنشاء حساب",
    QuestionMark: "؟"

  },
  placeholder: {
    email: "البريد الالكتروني",
    password: "الرقم السري",
    FirstName: "الاسم الاول",
    FistMiddleName: "الاسم الأوسط الأول",
    secondMiddleName: "الاسم الأوسط الثاني",
    LastName: "الاسم الاخير",
    ConfirmPassword: "تأكيد كلمة المرور",
    PhoneNumber: "رقم الهاتف",
    Gender: "الجنس",
    DateOfBirth: "تاريخ الميلاد",
    AccountType: "نوع الحساب",
    JobTitle: "مسمى وظيفي",
    NationalId: "الهوية الوطنية",
    Address: "العنوان",
    Province: "المحافظة",
    City: "المدينة",
    Country: "الدولة",
    Street: "الشارع",

  },
  applicationForm:{
    title: 'يرجى ملء التفاصيل لتلقي اتصال حول هذه الخدمه',
    serviceName: 'اسم الخدمة',
    phoneNumber: 'رقم الهاتف',
    serviceType: 'نوع الخدمة',
    selectBank: 'حدد البنك',
    note: 'ملحوظة',
    acknowledgment: 'أقر بموجب هذا وأسمح لـ BMAP بمشاركة التفاصيل المذكورة أعلاه مع مزودو الخدمات للاتصال بي والوصول إلى بياناتي من إدارة الائتمان الإماراتي حسب الحاجة لذلك. وعليه أوافق على الشروط والأحكام المدرجة.',
    applyNow: 'قدم الآن',
    phoneRequired: 'اسم الهاتف مطلوب',
    phonePattern: 'يجب أن يكون رقم الهاتف بالتنسيق الصحيح',
    bankRequired: 'البنك مطلوب',
    notesRequired: 'يجب عليك إضافة ملاحظات قبل المتابعة',
    terms: 'يجب عليك قبول الشروط للمتابعة',
  },
  requestedServices: {
    title: "الخدمات المطلوبة",
    service: "الخدمه",
    type: "نوع الخدمه",
    requestedDate: "تاريخ الطلب",
    bank: "البنك",
    status: "الحاله",
  },
  register: {
    register: "تسجيل ",
    back: "رجوع",
    next: "التالي",
    haveAcc: "لديك حساب ،",

  },
  status:{
    pending: "قيد الانتظار",
    approved: "موافق عليه",
    rejected: "مرفوض",
  },
  response: {
    error: "خطأ",
    success: "نجاح",
    unableToFetchAccDetails: "تعذر جلب تفاصيل الحساب",
    unableToCancelReq: "تعذر إلغاء الطلب",
    reqCancelled: "تم إلغاء الطلب",
    reqSent: "تم طلب الخدمة",
    failedToSubmitreq: "فشل فى طلب الخدمة",
    notLoggedIn: "يجب عليك تسجيل الدخول لطلب الخدمة",
    notApproved: "يجب الموافقة على حسابك لطلب الخدمة",
  },
  contact: {
    title: "أرسل لنا رسالة",
    subject: "الموضوع",
    message: "رسالتك",
    findus: "العنوان",
    ring: "اتصل بنا",
    legal: "المعلومات القانونية",
    contact: "اتصل",
    messageSent: "تم إرسال رسالتك بنجاح",
    messageError: "خطأ في إرسال الرسالة ، يرجى المحاولة مرة أخرى بعد قليل"
  },
  sent: "تم بنجاح",
  Request: "طلب",
  view: "المزيد",
  rejected: "سبب الرفض",
  confirm: "تأكيد",
  cancel: "إلغاء",
  profile: {
    title: "معلومات المستخدم",
    editProfileButton: "تغيير معلومات الملف الشخصي",
    changePasswordButton: "تغيير كلمة المرور",
    viewProfileInformationButton: "عرض معلومات الملف الشخصي",
    profilePictureLabel: "الصوره الشخصيه",
    nationalIdImagesLabel: "صور الهوية الوطنية",
    frontNationalIdImageLabel: "الصورة الأمامية للهوية الوطنية",
    backNationalIdImageLabel: "الصورة الخلفية للهوية الوطنية",
    oldPasswordLabel: "كلمة المرور القديمة",
    newPasswordLabel: "كلمة المرور الجديدة",
    saveButtonLabel: "حفظ",
    editProfileInfoLabel: "تغيير معلومات الملف الشخصي",
    editProfileInfoConfirmationMessage: "هل أنت متأكد أنك تريد تغيير معلومات ملفك الشخصي؟",
    editPasswordLabel: "تغيير كلمة المرور",
    editPasswordConfirmationMessage: "هل أنت متأكد أنك تريد تغيير كلمة المرور الخاصة بك؟",
    uploadProfilePictureLabel: "تحميل صورة الملف الشخصي",
    uploadButtonLabel: "تحميل",
    uploadNationalIdFrontLabel: "تحميل الصورة الأمامية للهوية الوطنية",
    uploadNationalIdBackLabel: "تحميل صورة الهوية الوطنية الخلفية",
  },
  offers: {
    Salary: "الحد الأدنى للراتب",
    Rate: "معدل",
    Annual: "رسوم سنوية",
    keys: "المزايا الرئيسية",
    apply: "قدم الآن",
    types: "أنواع",
    noOffers: "لا توجد عروض لهذه الخدمة بعد",
    Modaltitle:"تقديم طلب",

  }
}
