export const Arabic: any = {
  dir: "rtl",
  lang: "English",
  font: "cairoFont",
  navFloat: "",
  arabicClass: "arabic",
  rowReverse: "flex-row-reverse",
  menuStyle: "arabicMenu",
  menuCloseStyle: "arabicCloseButton",
  textAlign: "text-right",
  textAlignReverse: "text-left",
  FlexAlignItems: "align-items-end",
  NoRequest: "لا يوجد طلبات",
  flexDIr: "flex-row-reverse",
  copyRights1: "كل الحقوق محفوظة |",
  terms: "شروط",
  policy: "احكام",
  layout: {
    Home: "الرئيسية",
    about: "المزيد عنا",
    contact: "اتصل بنا",
    login: "الدخول",
    logout: "الخروج",
    service: "خدماتنا",
    requests: "طلبات الخدمات",
    links: "تصفح سريع",
    Loans: "Loans",
    personalLoans: "Personal Loans",
    accounts: "Accounts",
    investments: "Investments",
    creditCards: "Credit Cards",

  },
  Home: {
    More: "المزيد",
    aboutTitle: "لماذا نحن",
    AboutContent: "هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها.",
    creditTitle: "هل تبحث عن ميزة بطاقة ائتمان محددة؟",
    creditDesc: "نعمل كشريك لتقديم المنتجات والخدمات المالية التي تجعل الخدمات المصرفية آمنة وبسيطة ومريحة.",
    
  },
  about: {
    title1: "من نحن",
    content1: 'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. الهدف من استخدام لوريم إيبسوم هو أنه يحتوي على توزيع طبيعي -إلى حد ما- للأحرف ، بدلاً من استخدام "هنا يوجد محتوى نصي ، هنا يوجد محتوى نصي" ، مما يجعلها تبدو وكأنها إنجليزية قابلة للقراءة. تستخدم العديد من حزم النشر المكتبي ومحرري صفحات الويب الآن Lorem Ipsum كنص نموذج افتراضي ، وسيكشف البحث عن "lorem ipsum" عن العديد من مواقع الويب التي لا تزال في مهدها. تطورت إصدارات مختلفة على مر السنين ، أحيانًا عن طريق الصدفة ، وأحيانًا عن قصد (روح الدعابة المحقونة وما شابه ذلك).',
    title2: "لماذا نحن",
    content2: "هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها."
  },
  invalid: {
    invalidEmail: "البريد الالكتروني غير صحيح",
    requiredEmail: "ادخل البريد الالكتروني",
    emailPattern : "يجب أن يكون تنسيق البريد الإلكتروني صحيحًا",
    requiredPassword: "ادخل الرقم السري",
    InvalidPassword: "يجب أن يحتوي على حرف أبجدي صغير واحد على الأقل ، وحرف أبجدي كبير واحد على الأقل ، وحرف رقمي واحد على الأقل ، وحرف خاص واحد على الأقل ، ويجب أن يتكون من ثمانية أحرف أو أكثر.",
    InvalidConfirmPassword: "كلمة المرور غير مطابقة لتأكيد كلمة المرور ",
    requiredMobileNumber: "ادخل رقم الهاتف",
    InvalidMobileNumber: "رقم غير صحيح",
    InvalidName: "اسم غير صحيح",
    requiredDateOfBirth: "ادخل تاريخ الميلاد",
    requiredName: "ادخل الاسم",
    requiredAddress: "ادخل العنوان",
    requiredProvince: "ادخل المحافظة",
    requiredCountry: "ادخل البلد",
    requiredcity: "ادخل المدينة",
    requiredStreet: "ادخل الشارع",
    requiredJobTitle: "ادخل المسمي الوظيفي",
    requiredNationalID: "ادخل رقم الهوية",
    invalidNationalID:"رقم الهوية اقل من 14 رقم",
    namePattern: "يجب ألا يحتوي الاسم على أرقام أو رموز أو مسافات",
    invalidLogin: "تأكد من البيانات",
    invalidRegister: "خطأ في تقديم الطلب ، يرجى المحاولة مرة أخرى",
    loginRedirect: "سيتم إعادة توجيهك بعد قليل",
    required: "مطلوب",
  },
  subscribe: {
    subscribeNw: "اشترك الان",
    send: "ارسال",
    subscribed: "تم الاشتراك بالفعل",
  },
  serviceCarousel: {
    title: "نحن نقدم لك أنواع مختلفة من الخدمات",
    title2: "يوصى بأنواع مختلفة من الخدمات لك"

  },
  backsCarousel: {
    title: "المزودين المميزين",
    content: "هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها.",
  },
  login: {
    wlc: "مرحبا بك في",
    forgetPassword: "نسيت كلمة المرور؟ ",
    desc: "نسهل على الجميع الاستثمار في الخدمات المصرفية",
    login: "الدخول",
    donHaveAcc: "ليس لديك حساب ،",
    createAcc: "إنشاء حساب",
    QuestionMark: "؟"

  },
  placeholder: {
    email: "البريد الالكتروني",
    password: "الرقم السري",
    FirstName: "الاسم الاول",
    FistMiddleName: "الاسم الأوسط الأول",
    secondMiddleName: "الاسم الأوسط الثاني",
    LastName: "الاسم الاخير",
    ConfirmPassword: "تأكيد كلمة المرور",
    PhoneNumber: "رقم الهاتف",
    Gender: "الجنس",
    DateOfBirth: "تاريخ الميلاد",
    AccountType: "نوع الحساب",
    JobTitle: "مسمى وظيفي",
    NationalId: "الهوية الوطنية",
    Address: "العنوان",
    Province: "المحافظة",
    City: "المدينة",
    Country: "الدولة",
    Street: "الشارع",

  },
  applicationForm:{
    title: 'يرجى ملء التفاصيل لتلقي اتصال حول هذه الخدمه',
    serviceName: 'اسم الخدمة',
    phoneNumber: 'رقم الهاتف',
    serviceType: 'نوع الخدمة',
    selectBank: 'حدد البنك',
    note: 'ملحوظة',
    acknowledgment: 'أقر بموجب هذا وأسمح لـ Soulwallet بمشاركة التفاصيل المذكورة أعلاه مع المزود للاتصال بي والوصول إلى بياناتي من مكتب الائتمان المصري حسب الحاجة. أوافق على الشروط والأحكام المدرجة.',
    applyNow: 'قدم الآن',
    phoneRequired: 'اسم الهاتف مطلوب',
    phonePattern: 'يجب أن يكون رقم الهاتف بالتنسيق الصحيح',
    bankRequired: 'البنك مطلوب',
    notesRequired: 'يجب عليك إضافة ملاحظات قبل المتابعة',
    terms: 'يجب عليك قبول الشروط للمتابعة',
  },
  requestedServices: {
    title: "الخدمات المطلوبة",
    service: "الخدمه",
    type: "نوع الخدمه",
    requestedDate: "تاريخ الطلب",
    bank: "البنك",
    status: "الحاله",
  },
  register: {
    register: "تسجيل ",
    back: "رجوع",
    next: "التالي",
    haveAcc: "لديك حساب ،",

  },
  status:{
    pending: "قيد الانتظار",
    approved: "موافق عليه",
    rejected: "مرفوض",
  },
  response: {
    error: "خطأ",
    success: "نجاح",
    unableToFetchAccDetails: "تعذر جلب تفاصيل الحساب",
    unableToCancelReq: "تعذر إلغاء الطلب",
    reqCancelled: "تم إلغاء الطلب",
    reqSent: "تم طلب الخدمة",
    failedToSubmitreq: "فشل فى طلب الخدمة",
    notLoggedIn: "يجب عليك تسجيل الدخول لطلب الخدمة",
    notApproved: "يجب الموافقة على حسابك لطلب الخدمة",
  },
  contact: {
    title: "أرسل لنا رسالة",
    subject: "الموضوع",
    message: "رسالتك",
    findus: "أجدنا في المكتب",
    ring: "أعطنا مكالمه",
    legal: "المعلومات القانونية",
    contact: "اتصل",
    messageSent: "تم إرسال رسالتك بنجاح",
    messageError: "خطأ في إرسال الرسالة ، يرجى المحاولة مرة أخرى بعد قليل"
  },
  sent: "تم بنجاح",
  Request: "طلب",
  view: "المزيد",
  rejected: "سبب الرفض",
  confirm: "تأكيد",
  cancel: "إلغاء",
  profile: {
    title: "معلومات المستخدم",
    editProfileButton: "تغيير معلومات الملف الشخصي",
    changePasswordButton: "تغيير كلمة المرور",
    viewProfileInformationButton: "عرض معلومات الملف الشخصي",
    profilePictureLabel: "الصوره الشخصيه",
    nationalIdImagesLabel: "صور الهوية الوطنية",
    frontNationalIdImageLabel: "الصورة الأمامية للهوية الوطنية",
    backNationalIdImageLabel: "الصورة الخلفية للهوية الوطنية",
    oldPasswordLabel: "كلمة المرور القديمة",
    newPasswordLabel: "كلمة المرور الجديدة",
    saveButtonLabel: "حفظ",
    editProfileInfoLabel: "تغيير معلومات الملف الشخصي",
    editProfileInfoConfirmationMessage: "هل أنت متأكد أنك تريد تغيير معلومات ملفك الشخصي؟",
    editPasswordLabel: "تغيير كلمة المرور",
    editPasswordConfirmationMessage: "هل أنت متأكد أنك تريد تغيير كلمة المرور الخاصة بك؟",
    uploadProfilePictureLabel: "تحميل صورة الملف الشخصي",
    uploadButtonLabel: "تحميل",
    uploadNationalIdFrontLabel: "تحميل الصورة الأمامية للهوية الوطنية",
    uploadNationalIdBackLabel: "تحميل صورة الهوية الوطنية الخلفية",
  },
}
