export const English: any = {
  dir: "ltr",
  lang: "العربية",
  arabicClass: "",
  benefits: "Benefits & Features",
  textAlign: "text-left",
  textAlignReverse: "text-right",
  FlexAlignItems: "align-items-start",
  rowReverse: "",
  menuStyle: "",
  menuCloseStyle: "",
  navFloat: "float-right",
  quickLinks: "Quick Links",
  followUs: "Follow Us",
  copyRights1: "Copyright &copy; 2021, All rights reserved |",
  terms:"Terms",
  policy:"Policy",
  layout: {
    Home: "Home",
    about: "About Us",
    contact: "Contact Us",
    login: "Login",
    logout: "Logout",
    service: "Our services",
    requests: "Requested Services",
    links:"Links"
  },
  Home: {
    More: "More",
    aboutTitle: "Why us",
    AboutContent: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    creditTitle: " LOOKING FOR A SPECIFIC CREDIT CARD FEATURE?",
    creditDesc: "We work as a partner to provide financial products and services that make banking safe, simple and convenient.",
  },
  about: {
    title1: "Who We Are",
    content1: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    title2: "Why us",
    content2: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout."
  },
  invalid: {
    invalidEmail: "Invalid e-mail ",
    requiredEmail: "E-mail required ",
    emailPattern: "Email must be in a correct format (ex: example@mail.com)",
    requiredPassword: "Password required",
    InvalidPassword: "must contain at least 1 lowercase alphabetical character,  at least 1 uppercase alphabetical character ,at least 1 numeric character , at least one special character and must be eight characters or longer .",
    InvalidConfirmPassword:"password doesn't match confirm password",
    requiredMobileNumber: "Password required",
    InvalidMobileNumber: "Invalid Mobile Number",
    InvalidName: "Invalid Name",
    requiredDateOfBirth: "Date Of Birth required",
    requiredName: "Name required",
    requiredAddress: "Address required",
    requiredProvince: "Province required",
    requiredCountry: "Country required",
    requiredcity: "City required",
    requiredNationalID: "National ID required",
    invalidNationalID: "At least 14 digits",
    requiredStreet: "Street required",
    requiredJobTitle: "Job Title required",
    invalidLogin: "Enter valid email and password",
    invalidRegister: "Error submitting request, please try again.",
    namePattern: "name must not include digits, symbols or spaces",
    loginRedirect:"You will be redirected shortly",
    required: "Required",
  },
  subscribe: {
    send: "Send",
    subscribeNw: "Subscribe Now",
    subscribed: "you are already subscribed to our newsletter !",
  },
  serviceCarousel: {
    title: "We provide various kinds of services for you",
    title2:"Recommended various kinds of services for you"
  },
  backsCarousel:{
    title: "FEATURED PROVIDERS",
    content: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
  },
  login: {
    wlc: "Welcome to",
    forgetPassword: "Forgot Password? ",
    desc: "We make it easy for everyone to invest in banking services",
    login: "Login",
    donHaveAcc: "Don't have an account,",
    createAcc: "Create Account",
    QuestionMark:"?"
  },
  placeholder: {
    email: "Email",
    password: "Password",
    FirstName:"First Name",
    FistMiddleName:"First Middle Name",
    secondMiddleName:"Second Middle Name",
    LastName:"Last Name",
    ConfirmPassword:"Confirm Password",
    PhoneNumber: "Phone Number",
    Gender: "Gender",
    DateOfBirth: "Date Of Birth",
    AccountType:"Account Type",
    JobTitle:"Job Title",
    NationalId:"National ID",
    Address:"Address",
    Province:"Province",
    City:"City",
    Country: "Country",
    Street: "Street",
  },
  applicationForm:{
    title: 'Please fill in the details to receive a call back with more details about this product ',
    serviceName: 'Service Name',
    phoneNumber: 'Phone Number',
    serviceType: 'Service Type',
    selectBank: 'Select Bank',
    note: 'Note',
    acknowledgment: 'I hereby acknowledge and allow Soulwallet to share the above details with the provider to contact me & access my details from the Egyptian credit bureau as needed. I agree to the Terms and Conditions listed.',
    applyNow: 'Apply Now',
    phoneRequired: 'Phone name is required',
    phonePattern: 'Phone Number must be in a correct format',
    bankRequired: 'Bank is required',
    notesRequired: 'You must add notes before proceeding',
    terms: 'You must accept accept the terms to proceed',
  },
  requestedServices: {
    title: "Requested Services",
    service: "Service",
    type: "type",
    requestedDate: "Requested Date",
    bank: "Bank",
    status: "Status",
  },
  register: {
    register: "Register",
    back: "Back",
    next: "Next",
    haveAcc: "have an account,",

  },
  status:{
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
  },
  response: {
    error: "Error",
    success: "Success",
    unableToFetchAccDetails: "Unable to fetch account details",
    unableToCancelReq: "Unable to cancel request",
    reqCancelled: "Request cancelled",
    notLoggedIn: "You must be logged in to request a service",
  },
  contact: {
    title: "Send us a message",
    subject: "Subject",
    message: "Your Message",
    findus: "Find us at the office",
    ring: "Give us a ring",
    legal: "Legal information",
    contact: "Contact",
    messageSent: "Your message have been sent successfully.",
    messageError: "Error sending message, please try again shortly."
  },
  sent: "Done successfully",
  Request: "Request",
  confirm: "Confirm",
  cancel: "Cancel",
}
