export const English: any = {
  dir: "ltr",
  lang: "العربية",
  arabicClass: "",
  benefits: "Benefits & Features",
  textAlign: "text-left",
  textAlignReverse: "text-right",
  justifyContent: "justify-content-start",
  FlexAlignItems: "align-items-start",
  rowReverse: "",
  menuStyle: "",
  menuCloseStyle: "",
  navFloat: "float-right",
  quickLinks: "Quick Links",
  followUs: "Follow Us",
  copyRights1: "All rights reserved |",
  copyRights2: "Copyright ",
  terms:"Terms and Conditions",
  policy: "Privacy Policy",
  NoRequest: "No Requests Found",
  aboutHeaderOne: "Accurate and Transparent information ",
  aboutHeaderTwo: "Neutral comparisons ",
  aboutHeaderThree: "HIGH QUALITY INFORMATION",
  aboutHeaderFour: "UNIQUE TOOLS",
  layout: {
    Home: "Home",
    about: "About Us",
    contact: "Contact Us",
    login: "Login",
    logout: "Logout",
    service: "Our services",
    requests: "Requested Services",
    links: "Links",
    Loans:"Loans",
    personalLoans:"Personal Loans",
    accounts:"Accounts",
    investments:"Investments",
    creditCards:"Credit Cards",
    CorporateBanking:"Corporate",
    IslamicSolutions:"Islamic Solutions",

  },
  CorporateBanking :{
    type1: "Credit Card",
    type2: "Islamic Finance ",
    type3: "Accounts",
    type4:"Takaful"
  },
 IslamicSolutions :{
   type1: "Corporate banking Accounts ",
   type2:"Corporate Banking Finance and Facilities"
  },
  Home: {
    More: "Explore More",
    aboutTitle: "Why BMAP",
    AboutContent: "In terms of trading and research, we are committed to providing the best-in-class Financial brokerage service. Accurate and Transparent information You can now consult well- researched and organized product details, as well as comparison tools, before making an educated personal finance decision.",
    AboutContent1: "We are advocating on your behalf! We offer a neutral and unbiased opinion on all personal finance services, presenting you with all available options for selecting the best credit cards, loan offers, and the most exclusive financial solution.",
    creditTitle: " LOOKING FOR A SPECIFIC CREDIT CARD FEATURE?",
    creditDesc: "We work as a partner to provide financial products and services that make banking safe, simple and convenient.",
  },
  about: {
    title1: "About BMAP",
    content1: "We are a startup with a small but incredibly effective and enthusiastic team."+
"We assist you conduct consumer loan comparisons and compare credit cards within the UAE.within "+
"the process, we assist you identify the choices which will allow you to economize and luxuriate in the "+
"simplest perks.we've redefined “Comparison” during a way that has never been done before within the UAE.",
    title2: "How can we do it? ",
    content2: "First, we are a team of out-of-the-box thinkers with a deep understanding of the UAE consumer banking system. Our "+
"experience is within the areas of credit line, Underwriting, Sales & Distribution, Sales Strategy, Operations, Customer "+
"Service, Technology, and Marketing."+
"Our services allow our users to form the foremost of a good range of private finance solutions,"+
 " from Mastercard reward cards within the UAE, to non- public loans, to Islamic credit cards, applications, and more."
  },
  invalid: {  
    invalidEmail: "Invalid e-mail ",
    requiredEmail: "E-mail required ",
    emailPattern: "Email must be in a correct format (ex: example@mail.com)",
    requiredPassword: "Password required",
    InvalidPassword: "must contain at least 1 lowercase alphabetical character,  at least 1 uppercase alphabetical character ,at least 1 numeric character , at least one special character and must be eight characters or longer .",
    InvalidConfirmPassword:"password doesn't match confirm password",
    requiredMobileNumber: "Number required",
    requiredNationality: "Nationality required",
    requiredSalary: "Salary required",
    requiredTime: "Time required",
    InvalidMobileNumber: "Invalid number",
    InvalidName: "Invalid name",
    requiredDateOfBirth: "Date Of Birth required",
    requiredName: "Name required",
    requiredAddress: "Address required",
    requiredProvince: "Province required",
    requiredCountry: "Country required",
    requiredcity: "City required",
    requiredNationalID: "National ID required",
    invalidNationalID: "Invalid national ID",
    requiredStreet: "Street required",
    requiredJobTitle: "Job title required",
    invalidLogin: "Enter valid email and password",
    invalidRegister: "Error submitting request, please try again.",
    namePattern: "name must not include digits, symbols or spaces",
    loginRedirect:"You will be redirected shortly",
    required: "Required",
  },
  subscribe: {
    send: "Send",
    subscribeNw: "Need Help?",
    subscribed: "you are already subscribed to our newsletter !",
    subscribtionValidate:"please enter valide e-mail or phone number"
  },
  serviceCarousel: {
    title: "Our Services",
    title2:"Recommended various kinds of services for you"
  },
  backsCarousel:{
    title: "FEATURED PROVIDERS",
    content: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
  },
  login: {
    wlc: "Welcome to",
    forgetPassword: "Forgot Password? ",
    desc: "We make it easy for everyone to invest in banking services",
    login: "Login",
    donHaveAcc: "Don't have an account,",
    createAcc: "Create Account",
    QuestionMark:"?"
  },
  placeholder: {
    email: "Email",
    password: "Password",
    FirstName:"First Name",
    FistMiddleName:"First Middle Name",
    secondMiddleName:"Second Middle Name",
    LastName:"Last Name",
    ConfirmPassword:"Confirm Password",
    PhoneNumber: "Phone Number",
    Gender: "Gender",
    DateOfBirth: "Date Of Birth",
    AccountType:"Account Type",
    JobTitle:"Job Title",
    NationalId:"National ID",
    Address:"Address",
    Province:"Province",
    City:"City",
    Country: "Country",
    Street: "Street",
    salary: "Salary",
    Time:"Time to call",
    CompanyName:"Company Name",
    Comment: "Comment",
    nationality:'Nationality'
  },
  applicationForm:{
    title: 'Please fill in the details to receive a call back with more details about this product ',
    serviceName: 'Service Name',
    phoneNumber: 'Phone Number',
    serviceType: 'Service Type',
    selectBank: 'Select Bank',
    note: 'Note',
    acknowledgment: 'I hereby acknowledge and allow BMAP to share the above details with the provider to contact me & access my details from the UAE credit bureau as needed. I agree to the Terms and Conditions listed.',
    applyNow: 'Apply Now',
    phoneRequired: 'Phone name is required',
    phonePattern: 'Phone Number must be in a correct format',
    bankRequired: 'Bank is required',
    notesRequired: 'You must add notes before proceeding',
    terms: 'You must accept accept the terms to proceed',
  },
  requestedServices: {
    title: "Requested Services",
    service: "Service",
    type: "type",
    requestedDate: "Requested Date",
    bank: "Bank",
    status: "Status",
  },
  register: {
    register: "Register",
    back: "Back",
    next: "Next",
    haveAcc: "have an account,",

  },
  status:{
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
  },
  response: {
    error: "Error",
    success: "Success",
    unableToFetchAccDetails: "Unable to fetch account details",
    unableToCancelReq: "Unable to cancel request",
    reqCancelled: "Request cancelled",
    reqSent: "Request Sent",
    failedToSubmitreq: "Failed to submit request",
    notLoggedIn: "You must be logged in to request a service",
    notApproved: "Your account must be approved to request a service",
  },
  contact: {
    title: "Send us a message",
    subject: "Subject",
    message: "Your Message",
    findus: "Address",
    ring: "Call us",
    legal: "Legal information",
    contact: "Contact",
    messageSent: "Your message have been sent successfully.",
    messageError: "Error sending message, please try again shortly."
  },
  sent: "Done successfully",
  Request: "Request",
  view: "View",
  rejected: "Rejection Reason",
  confirm: "Confirm",
  cancel: "Cancel",
  profile: {
    title: "User Profile",
    editProfileButton: "Edit Profile Information",
    changePasswordButton: "Change Password",
    viewProfileInformationButton: "View Profile Information",
    profilePictureLabel: "Profile Picture",
    nationalIdImagesLabel: "National ID Images",
    frontNationalIdImageLabel:"National ID Front Image",
    backNationalIdImageLabel:"National ID Back Image",
    oldPasswordLabel:"Old Password",
    newPasswordLabel:"New Password",
    saveButtonLabel:"Save",
    editProfileInfoLabel:"Edit Profile Information",
    editProfileInfoConfirmationMessage:"Are you sure you want to edit your profile information ?",
    editPasswordLabel:"Edit Password",
    editPasswordConfirmationMessage:"Are you sure you want to edit your password ?",
    uploadProfilePictureLabel:"Upload Profile Picture",
    uploadButtonLabel:"Upload",
    uploadNationalIdFrontLabel:"Upload National ID Front Image",
    uploadNationalIdBackLabel:"Upload National ID Back Image",
  },
  offers: {
    Salary: "Minimum Salary",
    Rate: "Rate",
    Annual: "Annual Fee",
    keys: "Key benefits",
    apply: "Apply Now",
    types: "Types",
    noOffers: "There are no offers for this service yet",
    Modaltitle: "APPLY ONLINE",
    Quick: "Quick View",
    JoiningOffers: "Joining Offers ",
    KeyFeatures: "Key Features ",
    RewardFeatures: "Reward Features ",
    Things: "Things To Be Aware Of ",
  }

}
